disabled_rules:
  - function_parameter_count
  - function_body_length
  - type_body_length
  - force_try
  - force_cast
  - cyclomatic_complexity

included: 
  - Classes
  - FreetimeTests
  - Local Pods
excluded:
  - Pods
  - Playgrounds

reporter: "xcode"