language: objective-c
notifications:
  email: false
osx_image: xcode7.1
script: xctool -workspace "$TRAVIS_XCODE_WORKSPACE" -scheme "$TRAVIS_XCODE_SCHEME" test CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY=
xcode_workspace: MMMarkdown.xcworkspace
xcode_scheme:
  - MMMarkdown (iOS)
  - MMMarkdown (OS X)
  - MMMarkdown (tvOS)
  - MMMarkdown (watchOS)

