# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "210bed9d-a839-453c-8038-b28dd9a53932"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

lane :beta do
  match(app_identifier: ["com.logigear.githawk", "com.logigear.githawk.watchkitapp", 
                         "com.logigear.githawk.watchkitapp.watchkitextension"], 
        type: "development", readonly: true)
  gym(scheme: "Freetime-AppCenter", export_method: "development")
  crashlytics
  slack(message: "Successfully distributed a new beta build", channel: "auto-deploy")
end

lane :tests do
  run_tests(scheme: "Freetime-AppCenter")
end

lane :certificates do
  match(app_identifier: ["com.logigear.githawk", "com.logigear.githawk.watchkitapp", 
                         "com.logigear.githawk.watchkitapp.watchkitextension"], 
        type: "development")
end
