language: objective-c
osx_image: xcode9
before_install:
- brew update
- brew outdated carthage || brew upgrade carthage
- gem update fastlane --no-ri --no-rdoc --no-document
script:
- .travis/build.sh
after_success:
- bash <(curl -s https://codecov.io/bash)
notifications:
  email: false